<?php

namespace PrincipalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * centrosmedicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class centrosmedicosRepository extends EntityRepository
{

    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Product p ORDER BY p.name ASC'
            )
            ->getResult();
    }
	
}
