<?php

namespace PrincipalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * medicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class medicosRepository extends EntityRepository
{
}
