<?php

namespace PrincipalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * pacientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pacientesRepository extends EntityRepository
{
}
