<?php

namespace PrincipalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * visitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visitasRepository extends EntityRepository
{
}
